# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addRemoveSubjectsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRemoveSubject(object):
    def setupUi(self, AddRemoveSubject):
        AddRemoveSubject.setObjectName("AddRemoveSubject")
        AddRemoveSubject.resize(596, 583)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        AddRemoveSubject.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/planner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddRemoveSubject.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddRemoveSubject)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLbl = QtWidgets.QLabel(AddRemoveSubject)
        self.nameLbl.setObjectName("nameLbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLbl)
        self.nameLineEdit = QtWidgets.QLineEdit(AddRemoveSubject)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.courseYearLbl = QtWidgets.QLabel(AddRemoveSubject)
        self.courseYearLbl.setObjectName("courseYearLbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.courseYearLbl)
        self.courseYearComboBox = QtWidgets.QComboBox(AddRemoveSubject)
        self.courseYearComboBox.setObjectName("courseYearComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.courseYearComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.optionsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.optionsHorizontalLayout.setObjectName("optionsHorizontalLayout")
        self.subjectListVerticalLayout = QtWidgets.QVBoxLayout()
        self.subjectListVerticalLayout.setObjectName("subjectListVerticalLayout")
        self.label = QtWidgets.QLabel(AddRemoveSubject)
        self.label.setObjectName("label")
        self.subjectListVerticalLayout.addWidget(self.label)
        self.subjectListWidget = QtWidgets.QListWidget(AddRemoveSubject)
        self.subjectListWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.subjectListWidget.setObjectName("subjectListWidget")
        self.subjectListVerticalLayout.addWidget(self.subjectListWidget)
        self.optionsHorizontalLayout.addLayout(self.subjectListVerticalLayout)
        self.addRemoveLayout = QtWidgets.QVBoxLayout()
        self.addRemoveLayout.setObjectName("addRemoveLayout")
        self.addBtn = QtWidgets.QPushButton(AddRemoveSubject)
        self.addBtn.setEnabled(False)
        self.addBtn.setObjectName("addBtn")
        self.addRemoveLayout.addWidget(self.addBtn)
        self.removeBtn = QtWidgets.QPushButton(AddRemoveSubject)
        self.removeBtn.setEnabled(False)
        self.removeBtn.setObjectName("removeBtn")
        self.addRemoveLayout.addWidget(self.removeBtn)
        self.optionsHorizontalLayout.addLayout(self.addRemoveLayout)
        self.addedSubjectLayout = QtWidgets.QVBoxLayout()
        self.addedSubjectLayout.setObjectName("addedSubjectLayout")
        self.addedSubjectLbl = QtWidgets.QLabel(AddRemoveSubject)
        self.addedSubjectLbl.setObjectName("addedSubjectLbl")
        self.addedSubjectLayout.addWidget(self.addedSubjectLbl)
        self.addedSubjectListWidget = QtWidgets.QListWidget(AddRemoveSubject)
        self.addedSubjectListWidget.setObjectName("addedSubjectListWidget")
        self.addedSubjectLayout.addWidget(self.addedSubjectListWidget)
        self.optionsHorizontalLayout.addLayout(self.addedSubjectLayout)
        self.verticalLayout.addLayout(self.optionsHorizontalLayout)
        self.planHorizontalLayout = QtWidgets.QHBoxLayout()
        self.planHorizontalLayout.setObjectName("planHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.planHorizontalLayout.addItem(spacerItem)
        self.submitBtn = QtWidgets.QPushButton(AddRemoveSubject)
        self.submitBtn.setEnabled(False)
        self.submitBtn.setObjectName("submitBtn")
        self.planHorizontalLayout.addWidget(self.submitBtn)
        self.verticalLayout.addLayout(self.planHorizontalLayout)

        self.retranslateUi(AddRemoveSubject)
        QtCore.QMetaObject.connectSlotsByName(AddRemoveSubject)

    def retranslateUi(self, AddRemoveSubject):
        _translate = QtCore.QCoreApplication.translate
        AddRemoveSubject.setWindowTitle(_translate("AddRemoveSubject", "Add/Remove Subjects (Plan with Friends)"))
        self.nameLbl.setText(_translate("AddRemoveSubject", "Name:"))
        self.courseYearLbl.setText(_translate("AddRemoveSubject", "Course, Year: "))
        self.label.setText(_translate("AddRemoveSubject", "Subject List:"))
        self.addBtn.setText(_translate("AddRemoveSubject", ">"))
        self.removeBtn.setText(_translate("AddRemoveSubject", "<"))
        self.addedSubjectLbl.setText(_translate("AddRemoveSubject", "Added subjects:"))
        self.submitBtn.setText(_translate("AddRemoveSubject", "Submit"))
import ui.res.resources_rc
